### ISSUE TITLE
airscan doesn't work on jailbroken iOS device

### ISSUE THREAD

**Issue by razvand** [davidmurray/airscan#1]
Hi.

I've cloned airscan and its submodules and compiled it. I copied the airscan executable on a jailbroken iOS device using SSH, but it doesn't run. It gives me the result below.

```
Razvans-iPhone:~ root# ./airscan -s
[Error] Couldn't get WiFiDeviceClients.
Razvans-iPhone:~ root# ./airscan -s -v
First scan; creating necessary objects.
Creating WiFiManagerClient.
[Error] Couldn't get WiFiDeviceClients.
Razvans-iPhone:~ root# file airscan 
airscan: Mach-O fat file with 2 architectures
```

Should I do something else? Should I copy the entitlements file somewhere in the filesystem?

**Comment by davidmurray** [comment]
Try this (on your Mac):

```
git clone git://git.saurik.com/ldid.git
cd ldid
git submodule update --init
./make.sh
cp -f ./ldid $THEOS/bin/ldid`
```

And then recompile + reinstall.

**Comment by razvand** [comment]
Well, it's weird. I jut did a `make clean` and `make` and copied it again and now it's working properly. Sorry for the trouble.
